version: "3.8"
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: syncroniza/api
    ports:
      - "8000:8000"
    command:
      - npm
      - run
      - dev
    env_file:
      - ./server/.env
  demo-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: syncroniza/api
    ports:
      - "8001:8000"
    command:
      - npm
      - run
      - dev
    env_file:
      - ./server/.env.demo
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: syncroniza/nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - api
      - demo-api