version: "3.8"
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: syncroniza/api
    ports:
      - "8000:8000"
    command:
      - npm
      - run
      - dev
    env_file:
      - ./server/.env
  api-planner:
    image: syncroniza/api-planner
    ports:
      - "8002:8000"
    command:
      - npm
      - run
      - dev
  new-api:
    image: syncroniza/api
    ports:
      - "8003:3000"
    command:
      - npm
      - run
      - start
    env_file:
      - ./server/.env
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: syncroniza/nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - api
      - demo-api